version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      NODE_ENV: production
      CLAUDE_ROOT: /app/data/claude
      CODEX_ROOT: /app/data/codex
    volumes:
      - ${CLAUDE_LOGS_PATH:-${HOME}/.claude/projects}:/app/data/claude:ro
      - ${CODEX_LOGS_PATH:-${HOME}/.codex/sessions}:/app/data/codex:ro
    restart: unless-stopped
