version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLAUDE_ROOT: /app/data/claude
        NEXT_PUBLIC_CODEX_ROOT: /app/data/codex
        NEXT_PUBLIC_GEMINI_ROOT: ""
    ports:
      - "${APP_PORT:-8000}:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_CLAUDE_ROOT: /app/data/claude
      NEXT_PUBLIC_CODEX_ROOT: /app/data/codex
      NEXT_PUBLIC_GEMINI_ROOT: ""
      CLAUDE_ROOT: /app/data/claude
      CODEX_ROOT: /app/data/codex
    volumes:
      - ${CLAUDE_LOGS_PATH:-${HOME}/.claude/projects}:/app/data/claude:ro
      - ${CODEX_LOGS_PATH:-${HOME}/.codex/sessions}:/app/data/codex:ro
    restart: unless-stopped
