name: Prettier Check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@$(node -p "require('./package.json').packageManager.split('@')[1].split('+')[0]") --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Prettier formatting
        run: pnpm format
